model:
  task: detection
  name: yolox_x
  checkpoint:
    use_pretrained: True
    load_head: False
    path: ~
    fx_model_path: ~
    optimizer_path: ~
  freeze_backbone: False
  architecture:
    full: ~ # auto
    backbone:
      name: cspdarknet
      params:
        dep_mul: &dep_mul 1.33
        wid_mul: 1.25
        act_type: &act_type "silu"
      stage_params: ~
    neck:
      name: yolopafpn
      params:
        dep_mul: *dep_mul
        act_type: *act_type
    head:
      name: anchor_free_decoupled_head
      params:
        act_type: *act_type
  postprocessor: 
    score_thresh: 0.01  # decode
    nms_thresh: 0.65  # nms
    class_agnostic: False
  losses:
    - criterion: yolox_loss
      weight: ~
      l1_activate_epoch: 1